import 'antd/es/form/style/css'
import 'antd/es/button/style/css'
import 'antd/es/table/style/css'
import 'antd/es/modal/style/css'
import 'antd/es/message/style/css'
import '../../style'
import './index.css'
