import 'antd/es/spin/style/css'
import 'antd/es/modal/style/css'
import 'antd/es/alert/style/css'
import 'antd/es/message/style/css'
import 'antd/es/form/style/css'
import '../../style'
import './index.css'
